name: .NET Core

on:
  push:
    branches: [ main ]
    tags:
      - 'v*.*.*'
  pull_request:
    branches: [ main ]
env:
  DOTNET_NOLOGO: true
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    steps:
    - uses: actions/checkout@v2
    - name: Fetch all history for all tags and branches
      run: |
        git fetch --prune --unshallow
    - name: Setup .NET Core 6.0.400
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.400
    - name: Setup Node.js environment
      uses: actions/setup-node@v2.1.2
    - name: Build
      run: dotnet run --project ".\build\build.csproj" "test"
      env:
        DEVEXPRESS_NUGET_FEED: ${{secrets.DEVEXPRESS_NUGET_FEED}}
    - name: Publish
      if: ${{ runner.os == 'Windows' }}
      run: dotnet run --project ".\build\build.csproj" "publish" -s
      env:
        DEVEXPRESS_NUGET_FEED: ${{secrets.DEVEXPRESS_NUGET_FEED}}
        XENIAL_DEFAULTCONNECTIONSTRING: ${{secrets.XENIAL_DEFAULTCONNECTIONSTRING}}
    - name: Deploy
      if: ${{ runner.os == 'Windows' && startsWith(github.ref, 'refs/tags/v') }}
      run: dotnet run --project ".\build\build.csproj" "deploy" -s
      env:
        WEBDEPLOY_IP: ${{secrets.WEBDEPLOY_IP}}
        WEBDEPLOY_USER: ${{secrets.WEBDEPLOY_USER}}
        WEBDEPLOY_PASS: ${{secrets.WEBDEPLOY_PASS}}
